version: '2.1'
services:
  typescript-watch:
    build: .
    command: ./docker-command.sh
    ports:
      - "4488:4488"
      - "5082:5082"
    environment:
      - NODE_ENV=development
    network_mode: bridge
    volumes:
      - .:/app/
    volumes_from:
      - container:configs-volume:ro
